"""empty message

Revision ID: 2f79dabcbb5a
Revises: 
Create Date: 2023-09-15 00:19:08.143550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f79dabcbb5a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('esportsbattle_raw_data',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('game', sa.String(length=50), nullable=False),
    sa.Column('tour_name', sa.String(length=100), nullable=False),
    sa.Column('date_utc', sa.DateTime(), nullable=False),
    sa.Column('team_1', sa.String(length=50), nullable=False),
    sa.Column('team_2', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('esportsbattle_raw_data')
    # ### end Alembic commands ###
